---
- hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Create EC2
      ec2:
        key_name: testkey
        instance_tags:
          Name: test EC2
        region: ap-northeast-1
        instance_type: t2.micro
        image: ami-0ce107ae7af2e92b5
        group: demo sg devos
        wait: yes
        count: 1
        vpc_subnet_id: subnet-07962d9e4e67f1e74
        assign_public_ip: yes