---
- hosts: wasserver
  gather_facts: False
  become: true
  become_method: sudo
  
  tasks:    
    - name: update repos
      yum:
        name: "*"
        state: latest
    
    - name: install jdk
      yum:
        name: java-1.8.0-openjdk

    - name: setting java
      alternatives:
        name: java
        link: /usr/bin/java
        path: /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java

    - name: download tomcat
      get_url:
        url: https://mirror.dsrg.utoronto.ca/apache/tomcat/tomcat-8/v8.5.71/bin/apache-tomcat-8.5.71.tar.gz
        dest: /usr/local

    - name: copy tomcat
      unarchive:
        src: "/usr/local/apache-tomcat-8.5.71.tar.gz"
        dest: /usr/local
        remote_src: yes

    - name: renaming tomcat
      command: mv /usr/local/apache-tomcat-8.5.71 /usr/local/tomcat

    - name: starting tomcat
      shell: nohup /usr/local/tomcat/bin/startup.sh &

