---
- hosts: wasserver
  gather_facts: False
  become: true
  become_method: sudo

  tasks:    
    - name: download tomcat
      get_url:
        url: https://mirror.dsrg.utoronto.ca/apache/tomcat/tomcat-8/v8.5.71/bin/apache-tomcat-8.5.71.tar.gz
        dest: /usr/local

    - name: copy tomcat
      unarchive:
        src: "/usr/local/apache-tomcat-8.5.71.tar.gz"
        dest: /usr/local
        remote_src: yes

    - name: starting tomcat
      shell: nohup /usr/local/tomcat/bin/startup.sh &

