---
- hosts: webserver
  connection: local
  become: yes

  tasks:
    - name: Install apache packages
      shell: "yum install httpd"
      become: yes

    - name: apache start
      shell: "/bin/systemctl start httpd.service"
      become: yes

