---
- hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Create Security Group
      ec2_group:
        name: demo sg devos
        vpc_id: vpc-008f87d2173433eb1
        region: ap-northeast-1
        state: present
        description: allow 8080, 443 devos 
        tags:
          Name: demo sg devos
        rules:
        - proto: tcp
          ports:
          - 8080
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          ports:
          - 443
          cidr_ip: 0.0.0.0/0
